FROM python:3.8.5-slim

ENV APP /app
RUN mkdir $APP && mkdir $APP/data
WORKDIR $APP

EXPOSE 5000

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./gunicorn.conf.py ./service.py ./wsgi.py ./

ENTRYPOINT [ "gunicorn", "-c", "./gunicorn.conf.py", "wsgi" ]
