package de.jsmenues.backend.statistic;

import java.util.List;
import java.util.Objects;

/**
 * This class is used to send Data to the frontend.
 *
 * Property Getter and Setter autogenerated.
 * Equals & hashCode autogenerated.
 */
class StatisticPlotly {
    private String updateTime;
    private String title;
    private List<Object> traces;
    private Object layout;
    private List<Object> nextTrace;
    private List<Object> prevTrace;
    private String startDate;
    private String prevDate;
    private String nextDate;

    public String getPrevDate() {
        return prevDate;
    }

    public void setPrevDate(String prevDate) {
        this.prevDate = prevDate;
    }

    public String getNextDate() {
        return nextDate;
    }

    public void setNextDate(String nextDate) {
        this.nextDate = nextDate;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public void setNextTrace(List<Object> nextTrace) {
        this.nextTrace = nextTrace;
    }

    public void setPrevTrace(List<Object> prevTrace) {
        this.prevTrace = prevTrace;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<Object> getTraces() {
        return traces;
    }

    public void setTraces(List<Object> traces) {
        this.traces = traces;
    }

    public Object getLayout() {
        return layout;
    }

    public void setLayout(Object layout) {
        this.layout = layout;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public List<Object> getNextTrace() {
        return nextTrace;
    }

    public List<Object> getPrevTrace() {
        return prevTrace;
    }

    @Override
    public String toString() {
        return "StatisticPlotly{" +
                "updateTime='" + updateTime + '\'' +
                ", title='" + title + '\'' +
                ", traces=" + traces +
                ", layout=" + layout +
                ", nextTrace=" + nextTrace +
                ", prevTrace=" + prevTrace +
                ", startDate='" + startDate + '\'' +
                ", prevDate='" + prevDate + '\'' +
                ", nextDate='" + nextDate + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StatisticPlotly that = (StatisticPlotly) o;
        return Objects.equals(updateTime, that.updateTime) &&
                Objects.equals(title, that.title) &&
                Objects.equals(traces, that.traces) &&
                Objects.equals(layout, that.layout) &&
                Objects.equals(nextTrace, that.nextTrace) &&
                Objects.equals(prevTrace, that.prevTrace) &&
                Objects.equals(startDate, that.startDate) &&
                Objects.equals(prevDate, that.prevDate) &&
                Objects.equals(nextDate, that.nextDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(updateTime, title, traces, layout, nextTrace, prevTrace, startDate, prevDate, nextDate);
    }

}
